# Builds a JSON file from the main.json bicep

name: BicepBuild

on:
  push:
    paths: 
      - 'bicep/*'
      - ".github/workflows/bicepBuild.yml"
    branches-ignore: main
    
  pull_request:
    branches: main

  workflow_dispatch:
  
jobs:
  Validation:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: ContextCheck
        shell: pwsh
        run: | 
          echo 'ghen : ${{ github.event_name }}'
          dir

      - name: Install Bicep
        shell: pwsh
        run: |
          az bicep install

      - name: Bicep build
        shell: pwsh
        run: |
          #write-output $pwd
          $compiledir=Join-Path -Path $pwd -ChildPath "bicep/compiled"
          
          write-output $compiledir
          If(!(test-path $compiledir))
          {
                New-Item -ItemType Directory -Force -Path $compiledir
          }

          /home/runner/.azure/bin/bicep build bicep/main.bicep --outdir $compiledir

      - name: Git diff
        shell: pwsh
        id: isGitDiff
        run: |
          $diff=git diff --shortstat
          
          if ($null -eq $diff) {
            echo "::set-output name=GITDIFF::false" #outputting for condition
          }
          else {
            echo "::set-output name=GITDIFF::true" #outputting for condition
          }
          
          
      - name: GIT Push Json file
        if: ${{ steps.isGitDiff.outputs.GITDIFF}}
        uses: actions-x/commit@v2
        with:
          message: Adding auto compiled bicep json
